import { redirect } from "next/navigation";
import { db } from "@/lib/db";
import { getSession } from "@/lib/auth";
import { PERMISSIONS as P,hasPermission } from "@/lib/rbac";
import { marketingPhone } from "@/services/marketing";
import ActionForm from "../loyalty/action-form";
import MessageButton from "./message-button";
export default async function MarketingPage({searchParams}:{searchParams:Promise<{q?:string;campaign?:string}>}){
 const session=await getSession();if(!session?.branchId||!hasPermission(session.permissions,P.MARKETING_MANAGE))redirect("/dashboard");
 const query=await searchParams;const q=query.q?.trim().slice(0,100);
 const customers=await db.customer.findMany({where:{serviceOrders:{some:{branchId:session.branchId}},...(q?{OR:[{name:{contains:q}},{phone:q},{customerNo:q}]}:{})},include:{marketingConsents:{where:{branchId:session.branchId}}},orderBy:{createdAt:"desc"},take:50});
 const campaigns=await db.marketingCampaign.findMany({where:{branchId:session.branchId},orderBy:{createdAt:"desc"},take:50});
 const selected=campaigns.find(c=>c.id===query.campaign);
 return <main className="workspace"><a href="/dashboard/wash">← المغسلة</a><h1>رسائل وعروض المراكز</h1><p>حملات الفرع الحالي للعملاء الموافقين على القناة المختارة. تُفتح الرسالة في تطبيق SMS أو واتساب للمراجعة والإرسال يدويًا؛ التجهيز لا يعني الإرسال أو التسليم. الإرسال الآلي الجماعي يحتاج ربط مزوّد رسائل.</p><section className="panel"><h2>تجهيز عرض جديد</h2><ActionForm endpoint="marketing" action="campaign" label="حفظ مسودة العرض"><label>اسم العرض<input name="title" required maxLength={120}/></label><label>القناة<select name="channel"><option value="WHATSAPP">واتساب</option><option value="SMS">رسالة نصية SMS</option></select></label><label>نص العرض<textarea name="message" required maxLength={1000}/></label></ActionForm></section><section className="panel"><h2>العروض المحفوظة</h2>{campaigns.map(c=><p key={c.id}><a href={`?campaign=${c.id}`}>{c.title} — {c.channel==="SMS"?"رسائل نصية":"واتساب"}</a></p>)}{selected&&<blockquote style={{whiteSpace:"pre-wrap"}}>{selected.message}</blockquote>}</section><section className="panel"><h2>العملاء والموافقات — آخر 50 نتيجة</h2><form><input type="hidden" name="campaign" value={selected?.id??""}/><label>ابحث بالاسم أو رقم العميل أو الجوال<input name="q" defaultValue={q}/></label><button>بحث</button></form><p>الجوال المطلوب بصيغة دولية مثل ‎+966…‎. وثّق موافقة العميل لكل قناة، ويمكن إلغاؤها هنا فور طلبه.</p>{customers.map(c=>{const eligible=selected&&c.marketingConsents.some(x=>x.channel===selected.channel&&x.allowed&&x.phone===marketingPhone(c.phone)&&marketingPhone(c.phone));return <article className="panel" key={c.id}><h3>{c.name} — {c.customerNo}</h3><p dir="ltr">{c.phone??"بدون جوال"}</p><p>{c.marketingConsents.map(x=>`${x.channel}: ${x.allowed?"موافق":"موقوف"}`).join(" · ")||"لا توجد موافقات"}</p><details><summary>تسجيل موافقة أو إيقاف الرسائل</summary><ActionForm endpoint="marketing" action="consent" values={{customerId:c.id}} label="حفظ حالة الموافقة"><label>القناة<select name="channel"><option value="WHATSAPP">واتساب</option><option value="SMS">SMS</option></select></label><label>حالة العميل<select name="allowed" defaultValue="false"><option value="false">إيقاف الرسائل</option><option value="true">وافق على استقبال العروض</option></select></label><label>مرجع الموافقة أو طلب الإيقاف<input name="evidence" required minLength={3} maxLength={300}/></label></ActionForm></details>{selected&&eligible&&<MessageButton campaignId={selected.id} customerId={c.id}/>}</article>})}</section></main>;
}
