export const companyConfig = {
  legalNameAr: "شركة وجهتك الإبداعية لزيوت وخدمات السيارات",
  legalNameEn: "Your Creative Destination for Oil & Auto Services Company",
  companyAddress: "الرياض — حي طويق",
  branchAddress: "الرياض — حي طويق — شارع أحمد ابن الخطاب",
  brand: "YCD OIL",
  branch: "الرياض - حي طويق",
  operationalPhase: "PREOPENING",
  operationalPhaseAr: "مرحلة ما قبل التشغيل التجاري",
  preopening: {
    commercialOperationsStarted: false,
    fitOutReady: true,
    decorationsReady: true,
    toolsReady: true,
    equipmentReady: true,
    licensesReady: true,
    readinessSourceAr: "إفادة الإدارة بتاريخ 26/09/2026",
  },
  phone: "0535898340",
  email: "info@ycdoil.sa",
  website: "www.ycdoil.sa",
  unifiedNumber: "7038822883",
  crNumber: "1009014238",
  vatNumber: "311380910800003",
  group: {
    parentCompanyNameAr: "شركة الواجهات الإبداعية للمقاولات",
    relationshipAr: "الشركة الرئيسية الممولة للمشروع",
  },
  management: {
    generalManager: "أبوبكر نبيل سيف",
    branchManager: "حمزة عبدالرحمن سعيد الذبحاني",
    accountant: "هاني عبدالسلام الذبحاني",
    generalAccountant: "ضياء فرحان المخلافي",
    cashier: "عمار البخيتي",
    warehouse: "محمد نجيب عثمان حمادي",
    procurement: "حمزة عبدالرحمن سعيد الذبحاني",
    technicians: ["محمد نجيب عثمان حمادي", "عمار النابهي"],
    washSupervisor: "محمد المهدي ازهري",
    humanResources: "هاني عبدالسلام الذبحاني",
  },
  bank: {
    nameAr: "مصرف الراجحي",
    accountNameAr: "شركة وجهتك الإبداعية لخدمات السيارات",
    accountNumber: "528000010006080781162",
    iban: "SA7180000528608010781162",
    certificateReference: "55063515",
    certificateDate: "26/09/2026",
    certificateSourceAr: "خطاب IBAN المعتمد من مصرف الراجحي",
    certificateSha256: "121703866f6e01c3aaaacd8b3bed7befe6d9b02d342086ff087e63d7d5698dc6",
    openingBalance: 17000,
    openingBalanceAsOf: "29/09/2026",
    openingBalanceSourceAr: "إفادة الإدارة — الرصيد الافتتاحي المعتمد",
  },
  brandIdentity: {
    sourceAr: "ملف الهوية الرسمي YCD OIL المرفق من الإدارة",
    sourceSha256: "864c162d79433c1941393c2cb5cbe80ccef51abe291aea8018a84d7f0029549a",
    logoAsset: "/brand/ycd-logo-source.svg",
    approvedColors: ["#F18F21", "#F7A81D", "#939497", "#BDBDBF"],
  },
  vatRate: Number(process.env.VAT_RATE ?? "0.15"),
  washCouponValidityDays: Number(process.env.WASH_COUPON_VALIDITY_DAYS ?? "30"),
} as const;

export const brandColors = {
  orange: "#F18F21",
  gold: "#F7A81D",
  gray: "#939497",
  lightGray: "#BDBDBF",
  black: "#111111",
  white: "#FFFFFF",
} as const;
