export const operationalTeam = [
  {
    code: "YCD-001",
    nameAr: "أبوبكر نبيل سيف",
    primaryRoleAr: "المدير العام",
    responsibilitiesAr: ["الإدارة العامة", "الرقابة والإشراف العام"],
    systemRoleCodes: ["GENERAL_MANAGER"],
    systemRolesAr: ["المدير العام"],
  },
  {
    code: "YCD-002",
    nameAr: "حمزة عبدالرحمن سعيد الذبحاني",
    primaryRoleAr: "مدير الفرع",
    responsibilitiesAr: ["إدارة الفرع", "المشتريات"],
    systemRoleCodes: ["BRANCH_MANAGER", "PROCUREMENT"],
    systemRolesAr: ["مدير الفرع", "المشتريات"],
  },
  {
    code: "YCD-003",
    nameAr: "هاني عبدالسلام الذبحاني",
    primaryRoleAr: "المحاسب",
    responsibilitiesAr: ["المحاسبة", "الموارد البشرية"],
    systemRoleCodes: ["ACCOUNTANT", "HR_MANAGER"],
    systemRolesAr: ["المحاسب", "مدير الموارد البشرية"],
  },
  {
    code: "YCD-004",
    nameAr: "ضياء فرحان المخلافي",
    primaryRoleAr: "المحاسب العام",
    responsibilitiesAr: ["المحاسبة العامة"],
    systemRoleCodes: ["GENERAL_ACCOUNTANT"],
    systemRolesAr: ["المحاسب العام"],
  },
  {
    code: "YCD-005",
    nameAr: "عمار البخيتي",
    primaryRoleAr: "الكاشير",
    responsibilitiesAr: ["الكاشير والتحصيل"],
    systemRoleCodes: ["CASHIER"],
    systemRolesAr: ["الكاشير"],
  },
  {
    code: "YCD-006",
    nameAr: "محمد نجيب عثمان حمادي",
    primaryRoleAr: "مسؤول المستودع / فني",
    responsibilitiesAr: ["المستودع", "الخدمات الفنية"],
    systemRoleCodes: ["WAREHOUSE", "TECHNICIAN"],
    systemRolesAr: ["المستودع", "الفني"],
  },
  {
    code: "YCD-007",
    nameAr: "عمار النابهي",
    primaryRoleAr: "فني",
    responsibilitiesAr: ["الخدمات الفنية"],
    systemRoleCodes: ["TECHNICIAN"],
    systemRolesAr: ["الفني"],
  },
  {
    code: "YCD-008",
    nameAr: "محمد المهدي ازهري",
    primaryRoleAr: "مشرف المغسلة",
    responsibilitiesAr: ["الإشراف على المغسلة"],
    systemRoleCodes: ["WASH_SUPERVISOR"],
    systemRolesAr: ["مشرف المغسلة"],
  },
] as const;
