export const permissionLabels: Record<string, string> = {
  "marketing.manage": "إدارة العروض وموافقات الرسائل التسويقية",
  "dashboard.view": "عرض لوحة التحكم",
  "user.manage": "إدارة المستخدمين والصلاحيات",
  "operations.go_live": "اعتماد التشغيل التجاري",
  "operations.uat": "تسجيل اختبارات القبول",
  "service_order.create": "إنشاء أمر خدمة",
  "service_order.approve": "اعتماد أمر خدمة",
  "inventory.manage": "إدارة المخزون والأصناف",
  "inventory.issue": "صرف المخزون",
  "invoice.issue": "إصدار الفواتير",
  "payment.receive": "استلام المدفوعات",
  "customer.view": "عرض العملاء",
  "credit.manage": "إدارة الائتمان",
  "credit.sale": "البيع الآجل",
  "sales_return.process": "معالجة مرتجعات المبيعات",
  "shift.open": "فتح الوردية",
  "shift.close": "إقفال الوردية",
  "shift.variance.approve": "اعتماد فروقات الوردية",
  "finance.close.prepare": "إعداد الإقفال المالي",
  "finance.close.review": "مراجعة الإقفال المالي",
  "coupon.redeem": "استخدام كوبون الغسيل",
  "procurement.request": "طلب شراء",
  "procurement.quote": "إدارة عروض الموردين",
  "procurement.approve": "اعتماد المشتريات",
  "procurement.order": "إصدار أمر شراء",
  "procurement.receive": "استلام المشتريات",
  "supplier_invoice.create": "تسجيل فاتورة مورد",
  "supplier_invoice.approve_payment": "اعتماد سداد فاتورة مورد",
  "finance.view": "عرض المالية",
  "finance.manage": "إدارة الحسابات المالية",
  "finance.group_funding": "إدارة تمويل المجموعة",
  "finance.expense": "طلب مصروف",
  "finance.expense.approve": "اعتماد المصروف",
  "finance.expense.pay": "صرف المصروف",
  "finance.bank_reconcile": "إعداد المطابقة البنكية",
  "finance.bank_reconcile.review": "مراجعة المطابقة البنكية",
  "finance.transfer": "التحويل بين الحسابات",
  "pos.settle": "تسوية نقاط البيع",
  "supplier_payment.execute": "تنفيذ سداد المورد",
  "custody.request": "طلب عهدة",
  "custody.approve": "اعتماد العهدة",
  "custody.disburse": "صرف العهدة",
  "custody.settle": "تسوية العهدة",
  "custody.close": "إقفال العهدة",
  "hr.view": "عرض الموارد البشرية",
  "hr.manage": "إدارة بيانات الموظفين",
  "attendance.manage": "إدارة الحضور",
  "payroll.prepare": "إعداد الرواتب",
  "payroll.approve": "اعتماد الرواتب",
  "payroll.pay": "صرف الرواتب",
  "asset.view": "عرض الأصول",
  "asset.manage": "إدارة الأصول",
  "maintenance.manage": "إدارة الصيانة",
  "reports.view": "عرض التقارير",
  "audit.view": "عرض سجل التدقيق",
};
