import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { db } from "../lib/db";
import { PERMISSIONS } from "../lib/rbac";
import type { SessionPayload } from "../lib/auth";
import { performWashAction, washActionInTransaction } from "../services/wash-settlement";
import { completeServiceOrder } from "../services/service-order";
import { riyadhDateKey, riyadhDateRange } from "../lib/time";
async function main() {
  assert(process.env.ALLOW_UAT_FIXTURES === "true" && new URL(process.env.DATABASE_URL!).pathname.includes("uat") && process.env.NODE_ENV !== "production", "Isolated UAT database required");
  const suffix=randomUUID();
  const org=await db.organization.create({data:{nameAr:"Wash isolated test",brandName:"TEST"}});
  const source=await db.branch.create({data:{organizationId:org.id,nameAr:"Oil UAT",operationalStatus:"LIVE"}});
  const receiver=await db.branch.create({data:{organizationId:org.id,nameAr:"Wash UAT",operationalStatus:"LIVE"}});
  const user=await db.user.create({data:{username:`wash-fin-${suffix}`,name:"Finance UAT",branchId:source.id}});
  const washUser=await db.user.create({data:{username:`wash-operator-${suffix}`,name:"Wash UAT",branchId:receiver.id}});
  const session:SessionPayload={userId:user.id,branchId:source.id,name:user.name,username:user.username,mustChangePassword:false,sessionVersion:0,roles:[],permissions:Object.values(PERMISSIONS)};
  const operator={...session,userId:washUser.id,branchId:receiver.id,permissions:[PERMISSIONS.COUPON_REDEEM]};
  const account=await db.financialAccount.create({data:{branchId:source.id,code:"CASH",nameAr:"Source cash",type:"CASH"}});
  const receipt=await db.financialAccount.create({data:{branchId:receiver.id,code:"CASH",nameAr:"Wash cash",type:"CASH"}});
  await db.financialTransaction.create({data:{branchId:source.id,accountId:account.id,type:"OPENING_BALANCE",amount:1000,descriptionAr:"UAT",performedBy:user.id}});
  const agreementResult=await performWashAction(session,{action:"configure",nameAr:"Test wash",washBranchId:receiver.id,cadence:"WEEKLY"});
  const agreementId=(agreementResult as {agreementId:string}).agreementId;
  const customer=await db.customer.create({data:{name:"Repeat customer UAT"}});
  assert(customer.customerNo);
  const vehicle=await db.vehicle.create({data:{customerId:customer.id,plate:suffix, currentOdometer:1000}});
  const shift=await db.shift.create({data:{branchId:source.id,openedBy:user.id,openingCash:0}});
  const product=await db.product.create({data:{sku:`wash-test-${suffix}`,nameAr:"Eligible oil service",category:"SERVICE",unit:"service",salePrice:100,costPrice:0,minStock:0,grantsWashCoupon:true}});
  async function invoiceWithCoupon() {
    const order=await db.serviceOrder.create({data:{orderNo:randomUUID(),branchId:source.id,customerId:customer.id,vehicleId:vehicle.id,shiftId:shift.id,odometer:1000,status:"OPEN",items:{create:{productId:product.id,descriptionAr:product.nameAr,quantity:1,unitPrice:100,discount:0}}}});
    const invoice=await completeServiceOrder({branchId:source.id,actorId:user.id,serviceOrderId:order.id,paymentMethod:"CASH",nextServiceKm:6000,nextServiceAt:new Date("2030-01-01T00:00:00+03:00"),idempotencyReference:randomUUID()});
    assert.equal(invoice.coupons.length,1);
    const history=await db.vehicleHistory.findFirstOrThrow({where:{serviceOrderId:order.id}});assert.equal(history.nextServiceKm,6000);
    const repeated=await completeServiceOrder({branchId:source.id,actorId:user.id,serviceOrderId:order.id,paymentMethod:"CASH",idempotencyReference:randomUUID()});assert.equal(repeated.id,invoice.id);
    return invoice.coupons[0];
  }
  const coupon=await invoiceWithCoupon();
  await assert.rejects(()=>performWashAction({...operator,permissions:[]},{action:"redeem",serial:coupon.serial}),/FORBIDDEN/);
  await assert.rejects(()=>performWashAction(session,{action:"redeem",serial:coupon.serial}),/WASH_AGREEMENT_REQUIRED/);
  const races=await Promise.allSettled([1,2].map(()=>performWashAction(operator,{action:"redeem",serial:coupon.serial})));
  assert.equal(races.filter(r=>r.status==="fulfilled").length,1);
  assert.equal(await db.washService.count({where:{couponId:coupon.id}}),1);
  const service=await db.washService.findUniqueOrThrow({where:{couponId:coupon.id}});assert.equal(service.amount,null);
  await assert.rejects(()=>performWashAction(operator,{action:"redeem",serial:coupon.serial}),/COUPON_NOT_ACTIVE/);
  await performWashAction(operator,{action:"complete",serviceId:service.id});
  const businessDate=riyadhDateKey(new Date());
  assert.equal(riyadhDateRange("2026-09-30","2026-09-30")!.start.toISOString(),"2026-09-29T21:00:00.000Z");
  await assert.rejects(()=>performWashAction(operator,{action:"submit",agreementId,businessDate,key:randomUUID()}),/VALUATION_REQUIRED/);
  await assert.rejects(()=>performWashAction(operator,{action:"value",serviceId:service.id,amount:"20"}),/FORBIDDEN/);
  await performWashAction(session,{action:"value",serviceId:service.id,amount:"20.50"});
  const submit={action:"submit" as const,agreementId,businessDate,key:randomUUID()};
  const raised=await performWashAction(operator,submit) as {batchId:string};assert.deepEqual(await performWashAction(operator,submit),raised);
  await assert.rejects(()=>performWashAction(operator,{...submit,key:randomUUID()}),/NO_COMPLETED_SERVICES/);
  const pay={action:"pay" as const,batchId:raised.batchId,amount:"10.25",accountId:account.id,receiptAccountId:receipt.id,reference:"UAT-TRANSFER",key:randomUUID()};
  await assert.rejects(()=>performWashAction(session,pay),/BATCH_NOT_POSTED/);
  await assert.rejects(()=>performWashAction({...session,userId:washUser.id},{action:"post",batchId:raised.batchId}),/INDEPENDENT_REVIEW_REQUIRED/);
  await performWashAction(session,{action:"post",batchId:raised.batchId});
  await assert.rejects(()=>performWashAction(session,{action:"value",serviceId:service.id,amount:"99"}),/SERVICE_ALREADY_BATCHED/);
  await assert.rejects(()=>performWashAction(session,{...pay,amount:"21"}),/PAYMENT_EXCEEDS_BALANCE/);
  await assert.rejects(()=>performWashAction(session,{...pay,receiptAccountId:account.id}),/INVALID_ACCOUNTS/);
  await assert.rejects(()=>db.$transaction(async tx=>{await washActionInTransaction(tx,session,pay);throw new Error("ROLLBACK_PROBE")}),/ROLLBACK_PROBE/);
  assert.equal(await db.washSettlement.count({where:{batchId:raised.batchId}}),0);
  assert.equal(await db.financialTransaction.count({where:{relatedEntityType:"WashBatch",relatedEntityId:raised.batchId}}),0);
  const payments=await Promise.allSettled([1,2].map(()=>performWashAction(session,pay)));assert(payments.some(r=>r.status==="fulfilled"));
  await performWashAction(session,pay); // retry of an uncertain outcome must not add another payment
  assert.equal(await db.washSettlement.count({where:{batchId:raised.batchId}}),1);
  await performWashAction(session,{...pay,key:randomUUID(),reference:"FINAL"});
  await assert.rejects(()=>performWashAction(session,{...pay,key:randomUUID()}),/PAYMENT_EXCEEDS_BALANCE/);
  const batch=await db.washBatch.findUniqueOrThrow({where:{id:raised.batchId},include:{payments:true}});
  assert.equal(batch.payments.reduce((n,p)=>n+Number(p.amount),0),20.5);
  const paired=await db.financialTransaction.findMany({where:{relatedEntityType:"WashBatch",relatedEntityId:raised.batchId}});assert.equal(paired.length,4);assert.equal(paired.reduce((n,t)=>n+Number(t.amount),0),0);
  await performWashAction(session,{action:"configure",nameAr:"Test wash",washBranchId:receiver.id,cadence:"MONTHLY",issueMode:"ALL",unitAmount:"30"});
  await db.product.update({where:{id:product.id},data:{grantsWashCoupon:false}});
  const coupon2=await invoiceWithCoupon();await db.coupon.update({where:{id:coupon2.id},data:{expiresAt:new Date("2000-01-01")}});
  await assert.rejects(()=>performWashAction(operator,{action:"redeem",serial:coupon2.serial}),/COUPON_EXPIRED/);
  assert.equal(await db.washService.count({where:{couponId:coupon2.id}}),0);
  console.log("PASS: service → invoice → coupon → reminder; scoped redemption, concurrency, valuation, daily claims, independent posting, partial/full payments, rollback, idempotency and balanced center/wash cash entries.");
}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>db.$disconnect());
