import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { Prisma } from "@prisma/client";
import { db } from "../lib/db";
import { PERMISSIONS as P } from "../lib/rbac";
import type { SessionPayload } from "../lib/auth";
import { performMedadAction,medadActionInTransaction,medadActionSchema } from "../services/medad/actions";
import { exportMedadDraft } from "../services/medad/export";
import { captureMedad } from "../services/medad/outbox";
import { checkMedadConnection,validatedBaseUrl,medadRuntime } from "../lib/medad/client";
import { completeServiceOrder,completeServiceOrderInTransaction } from "../services/service-order";
import { processSalesReturn } from "../services/sales-return";
import { riyadhDateKey } from "../lib/time";
async function main(){
 assert(process.env.ALLOW_UAT_FIXTURES==="true"&&new URL(process.env.DATABASE_URL!).pathname.includes("uat")&&process.env.NODE_ENV!=="production","Isolated UAT database required");
 const suffix=randomUUID();
 const org=await db.organization.create({data:{nameAr:"Medad UAT",brandName:"TEST"}});
 const branch=await db.branch.create({data:{organizationId:org.id,nameAr:"Oil UAT",operationalStatus:"LIVE"}});
 const other=await db.branch.create({data:{organizationId:org.id,nameAr:"Other UAT",operationalStatus:"LIVE"}});
 const user=await db.user.create({data:{username:`medad-${suffix}`,name:"UAT",branchId:branch.id}});
 const session:SessionPayload={userId:user.id,branchId:branch.id,name:user.name,username:user.username,mustChangePassword:false,sessionVersion:0,roles:[],permissions:Object.values(P)};
 const config={action:"configure" as const,captureEnabled:"true" as const,subscriptionId:"medadUAT",medadBranch:1,fiscalYear:"",warehouseNo:"WH01",costCenterNo:"CC01",salesmanId:"S01",invoiceAuthority:"MEDAD" as const};
 await assert.rejects(()=>performMedadAction({...session,permissions:[]},config),/FORBIDDEN/);
 await performMedadAction(session,config);await performMedadAction({...session,branchId:other.id},{...config,captureEnabled:"false"});
 const customer=await db.customer.create({data:{name:"UAT customer"}});
 const vehicle=await db.vehicle.create({data:{customerId:customer.id,plate:suffix}});
 const shift=await db.shift.create({data:{branchId:branch.id,openedBy:user.id}});
 await db.financialAccount.create({data:{branchId:branch.id,code:"CASH",nameAr:"Cash",type:"CASH"}});
 const product=await db.product.create({data:{sku:suffix,nameAr:"UAT wash",category:"SERVICE",unit:"wash",salePrice:40,costPrice:0}});
 const makeOrder=()=>db.serviceOrder.create({data:{channel:"WASH",orderNo:randomUUID(),branchId:branch.id,customerId:customer.id,vehicleId:vehicle.id,shiftId:shift.id,status:"OPEN",items:{create:{productId:product.id,descriptionAr:product.nameAr,quantity:2,unitPrice:40,discount:10}}}});
 const input=(id:string)=>({serviceOrderId:id,branchId:branch.id,actorId:user.id,paymentMethod:"CASH" as const,idempotencyReference:randomUUID()});
 const rolled=await makeOrder();
 await assert.rejects(()=>db.$transaction(async tx=>{await completeServiceOrderInTransaction(tx,input(rolled.id));throw Error("ROLLBACK");}),/ROLLBACK/);
 assert.equal(await db.medadOutbox.count({where:{branchId:branch.id}}),0);assert.equal(await db.invoice.count({where:{serviceOrderId:rolled.id}}),0);
 const invoice=await completeServiceOrder(input(rolled.id));await completeServiceOrder(input(rolled.id));
 assert.equal(await db.medadOutbox.count({where:{branchId:branch.id}}),2);
 const entry=await db.medadOutbox.findUniqueOrThrow({where:{branchId_kind_sourceId:{branchId:branch.id,kind:"INVOICE",sourceId:invoice.id}}});
 await performMedadAction(session,{action:"prepare",id:entry.id});
 assert.equal((await db.medadOutbox.findUniqueOrThrow({where:{id:entry.id}})).status,"NEEDS_DATA");
 await assert.rejects(()=>performMedadAction({...session,branchId:other.id},{action:"prepare",id:entry.id}),/ENTRY_NOT_FOUND/);
 const map=async(kind:"CUSTOMER"|"PRODUCT"|"UNIT"|"PAYMENT_METHOD"|"VAT",localId:string,remoteId:string)=>performMedadAction(session,{action:"map",kind,localId,remoteId,note:"UAT mapping"});
 await assert.rejects(()=>performMedadAction({...session,branchId:other.id},{action:"map",kind:"CUSTOMER",localId:customer.id,remoteId:"C1",note:"UAT wrong branch"}),/LOCAL_ENTITY_NOT_FOUND/);
 await map("CUSTOMER",customer.id,"C001");await map("PRODUCT",product.id,"P001");await map("UNIT","wash","EA");await map("PAYMENT_METHOD","CASH","0");await map("VAT","15","1");
 await assert.rejects(()=>map("PAYMENT_METHOD","CARD","15"),/LOCAL_ENTITY_NOT_FOUND/);
 await assert.rejects(()=>performMedadAction(session,{...config,subscriptionId:"DifferentTenant"}),/CONFIG_LOCKED/);
 await performMedadAction(session,{action:"prepare",id:entry.id});
 const exported=await exportMedadDraft(session,entry.id);assert.equal(exported.status,"PREPARED");
 const draft=exported.draft as {mode:string;medadCandidate:{referenceNo:string;paymentType:number;total:number;totalTax:number;net:number;Order_Detail:{lineDiscount:number}[]}};
 assert.equal(draft.mode,"REVIEW_ONLY");assert.equal(draft.medadCandidate.total,70);assert.equal(draft.medadCandidate.totalTax,10.5);assert.equal(draft.medadCandidate.net,80.5);assert.equal(draft.medadCandidate.paymentType,0);assert.equal(draft.medadCandidate.Order_Detail[0].lineDiscount,10);assert.equal(draft.medadCandidate.referenceNo,`YCD:${invoice.id}`);
 await assert.rejects(()=>exportMedadDraft({...session,branchId:other.id},entry.id),/ENTRY_NOT_FOUND/);
 await assert.rejects(()=>exportMedadDraft({...session,permissions:[]},entry.id),/FORBIDDEN/);
 const view={...session,permissions:[P.INTEGRATION_VIEW]};await exportMedadDraft(view,entry.id);await assert.rejects(()=>performMedadAction(view,{action:"prepare",id:entry.id}),/FORBIDDEN/);
 await db.invoice.update({where:{id:invoice.id},data:{status:"ISSUED"}});await assert.rejects(()=>exportMedadDraft(session,entry.id),/STALE_DRAFT/);await db.invoice.update({where:{id:invoice.id},data:{status:"PAID"}});
 await map("PRODUCT",product.id,"P002");await assert.rejects(()=>exportMedadDraft(session,entry.id),/STALE_DRAFT/);
 const today=riyadhDateKey(new Date());await performMedadAction(session,{action:"scan",from:today,to:today});await performMedadAction(session,{action:"scan",from:today,to:today});assert.equal(await db.medadOutbox.count({where:{branchId:branch.id}}),2);
 await assert.rejects(()=>performMedadAction(session,{action:"scan",from:"2026-01-01",to:"2026-12-31"}),/EXPORT_LIMIT/);
 const receipt=await db.medadOutbox.findFirstOrThrow({where:{branchId:branch.id,kind:"PAYMENT"}});await performMedadAction(session,{action:"prepare",id:receipt.id});assert.equal((await exportMedadDraft(session,receipt.id)).status,"NOT_SUPPORTED");
 const line=await db.serviceOrderItem.findFirstOrThrow({where:{serviceOrderId:rolled.id}});
 await processSalesReturn({invoiceId:invoice.id,branchId:branch.id,actorId:user.id,reason:"UAT partial return",refundMethod:"CASH",idempotencyReference:randomUUID(),items:[{serviceOrderItemId:line.id,quantity:1}]});
 assert.equal(await db.medadOutbox.count({where:{branchId:branch.id,kind:"RETURN"}}),1);
 await performMedadAction(session,{action:"prepare",id:entry.id});const returned=await db.medadOutbox.findUniqueOrThrow({where:{id:entry.id}});assert.equal(returned.status,"NEEDS_DATA");assert((returned.issues as string[]).includes("RETURNED_INVOICE_REVIEW"));
 // Configuration changes and preparation are transactional; aborted changes cannot leak.
 const old=await db.medadConnection.findUniqueOrThrow({where:{branchId:branch.id}});
 await assert.rejects(()=>db.$transaction(async tx=>{await medadActionInTransaction(tx,session,{...config,warehouseNo:"BAD"});throw Error("ROLLBACK");}),/ROLLBACK/);assert.equal((await db.medadConnection.findUniqueOrThrow({where:{branchId:branch.id}})).revision,old.revision);
 await db.$transaction(tx=>captureMedad(tx,other.id,"INVOICE","not-created","NOT-CAPTURED"));assert.equal(await db.medadOutbox.count({where:{branchId:other.id}}),0);
 assert.equal(medadActionSchema.safeParse({action:"send",id:entry.id}).success,false);
 // Contract test uses a fake transport exclusively. No external messages or finance requests.
 const calls:{url:string;method:string}[]=[];
 const runtime={baseUrl:"https://tenant.example.invalid/api",username:"uat-user",password:"uat-password",tokenField:"data.token"};
 const login={subscriptionId:"uat",branch:1,year:""};
 const fake:typeof fetch=async(url,init)=>{calls.push({url:String(url),method:init?.method??"GET"});assert.equal(init?.redirect,"error");if(String(url).endsWith("/getToken")){const body=JSON.parse(String(init?.body));assert.equal(body.subscriptionId,"uat");assert.equal(body.password,runtime.password);return Response.json({data:{token:"uat-only-token-value"}});}assert.equal((init?.headers as Record<string,string>).authorization,"Bearer uat-only-token-value");return Response.json({items:[{warehouseNo:"WH01",warehouseName:"Test"}]});};
 assert.deepEqual(await checkMedadConnection(runtime,login,fake),{warehouseCountOnFirstPage:1});assert.equal(calls.length,2);assert(calls.every(c=>c.method==="GET"||c.url.endsWith("/getToken")));
 await assert.rejects(()=>checkMedadConnection(runtime,login,async()=>Response.json({error:"SECRET-MUST-NOT-LEAK"},{status:403})),/^Error: REMOTE_AUTH_FAILED$/);
 await assert.rejects(()=>checkMedadConnection(runtime,login,async()=>Response.json({token:"wrong-field"})),/REMOTE_RESPONSE_INVALID/);
 await assert.rejects(()=>checkMedadConnection(runtime,login,async()=>{throw Error("secret failure message");}),/^Error: REMOTE_UNAVAILABLE$/);
 for(const host of ["http://tenant.example.invalid","https://api-docs.medaderp.com","https://127.0.0.1","https://localhost","https://u:p@tenant.example.invalid","https://tenant.example.invalid/?q=secret"])assert.throws(()=>validatedBaseUrl(host),/UNSUPPORTED_REMOTE_HOST/);
 const prior=process.env.MEDAD_READ_CHECK_ENABLED;delete process.env.MEDAD_READ_CHECK_ENABLED;assert.throws(()=>medadRuntime(branch.id),/READ_CHECK_NOT_ENABLED/);if(prior)process.env.MEDAD_READ_CHECK_ENABLED=prior;
 console.log("PASS: atomic invoice/payment/return capture; local deduplication; exact draft totals; mapping validation; branch and role isolation; stale exports rejected; configuration rollback; unsupported payment dispatch blocked; read-only Medad transport with redacted failures. No live Medad requests or accounting writes.");
}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>db.$disconnect());
