import { redirect } from "next/navigation";
import { db } from "@/lib/db";
import { getSession } from "@/lib/auth";
import { PERMISSIONS as P,hasPermission } from "@/lib/rbac";
import { riyadhDateKey } from "@/lib/time";
import { kindLabels,statusLabels,mappingLabels } from "@/lib/medad/contract";
import { MedadForm,MappingForm } from "./medad-form";
export default async function MedadPage({searchParams}:{searchParams:Promise<{q?:string;page?:string}>}) {
 const session=await getSession();if(!session?.branchId||![P.INTEGRATION_VIEW,P.INTEGRATION_MANAGE].some(p=>hasPermission(session.permissions,p)))redirect("/dashboard");
 const branchId=session.branchId;const can=hasPermission(session.permissions,P.INTEGRATION_MANAGE);const query=await searchParams;const q=query.q?.trim().slice(0,100)??"";const page=Math.min(10000,Math.max(1,Number(query.page)||1));
 const [config,mappings,entries,totals,customers,products,accounts,branch]=await Promise.all([
 db.medadConnection.findUnique({where:{branchId}}),db.medadMapping.findMany({where:{branchId},orderBy:{kind:"asc"}}),db.medadOutbox.findMany({where:{branchId},orderBy:[{capturedAt:"desc"},{id:"desc"}],skip:(Math.floor(page)-1)*50,take:50}),db.medadOutbox.groupBy({by:["status"],where:{branchId},_count:{_all:true}}),
 db.customer.findMany({where:{serviceOrders:{some:{branchId}},...(q?{OR:[{name:{contains:q}},{customerNo:{contains:q}},{phone:q}]}:{})},take:100,orderBy:{name:"asc"}}),db.product.findMany({where:q?{OR:[{nameAr:{contains:q}},{sku:{contains:q}}]}:{},take:100,orderBy:{nameAr:"asc"}}),db.financialAccount.findMany({where:{branchId},orderBy:{nameAr:"asc"}}),db.branch.findUniqueOrThrow({where:{id:branchId}})]);
 const units=await db.product.findMany({select:{unit:true},distinct:["unit"],orderBy:{unit:"asc"}});
 const choices={CUSTOMER:customers.map(c=>({id:c.id,label:`${c.customerNo} — ${c.name}`})),PRODUCT:products.map(p=>({id:p.id,label:`${p.sku} — ${p.nameAr}`})),UNIT:units.map(p=>({id:p.unit,label:p.unit})),ACCOUNT:accounts.map(a=>({id:a.id,label:`${a.code} — ${a.nameAr}`})),PAYMENT_METHOD:[{id:"CASH",label:"نقد"},{id:"CARD",label:"بطاقة"},{id:"TRANSFER",label:"تحويل"},{id:"CREDIT",label:"آجل"}]};
 const today=riyadhDateKey(new Date());
 return <main className="workspace"><a href="/dashboard" className="backLink">← لوحة التحكم</a><h1>الربط المحاسبي — مداد</h1><p>{branch.nameAr} · تجهيز المطابقات ومراجعة العمليات قبل الربط الفعلي.</p><section className="panel"><h2>الحالة: تجهيز ومراجعة فقط</h2><p>مداد هو المرجع المستهدف للتقارير والقوائم المالية. الإرسال المحاسبي غير مفعّل؛ لا توجد عمليات مرسلة من هذه الصفحة. اختيار جهة الفاتورة أدناه يسجل قرار التكييف المقترح ولا يغيّر إصدار الفواتير الحالي.</p><p>يلزم تزويد مسؤول النظام بعنوان API الفعلي وبيانات حساب الربط والاشتراك والفرع، وتأكيد سياسة الفواتير والتحصيل ومنع التكرار مع مداد. الأسرار تُضبط في الخادم ولا تُدخل في هذه الصفحة.</p><p>التقاط العمليات الجديدة: {config?.captureEnabled?"مفعّل في سجل المراجعة المحلي":"متوقف"}. تشغيل الالتقاط لا يرسل شيئًا إلى مداد.</p></section>
 <section className="kpis reportKpis">{totals.map(t=><article key={t.status}><span>{statusLabels[t.status]}</span><b>{t._count._all}</b></article>)}</section>
 {can&&<details className="panel" open={!config}><summary>إعداد ربط الفرع</summary><MedadForm action="configure" label="حفظ إعداد المراجعة"><label>رقم الاشتراك لدى مداد<input name="subscriptionId" defaultValue={config?.subscriptionId??""} maxLength={255}/></label><label>رقم فرع مداد<input name="medadBranch" type="number" min="0" step="1" defaultValue={config?.medadBranch??""}/></label><label>السنة المالية — اتركها فارغة للسنة الحالية<input name="fiscalYear" maxLength={4} defaultValue={config?.fiscalYear??""}/></label><label>رقم مخزن مداد<input name="warehouseNo" maxLength={10} defaultValue={config?.warehouseNo??""}/></label><label>مركز التكلفة<input name="costCenterNo" maxLength={50} defaultValue={config?.costCenterNo??""}/></label><label>رمز مندوب المبيعات<input name="salesmanId" maxLength={30} defaultValue={config?.salesmanId??""}/></label><label>الجهة المقترحة لإصدار الفاتورة الرسمية<select name="invoiceAuthority" defaultValue={config?.invoiceAuthority??"UNCONFIRMED"}><option value="UNCONFIRMED">بانتظار قرار الحسابات</option><option value="MEDAD">مداد</option><option value="YCD">YCD OIL</option></select></label><label>التقاط العمليات الجديدة للمراجعة<select name="captureEnabled" defaultValue={String(config?.captureEnabled??false)}><option value="false">متوقف</option><option value="true">مفعّل — دون إرسال خارجي</option></select></label></MedadForm><MedadForm action="check" label="اختبار المصادقة وقراءة المخازن فقط"/></details>}
 {can&&config&&<section className="panel"><h2>مطابقة بيانات النظامين</h2><form><label>ابحث عن العميل أو الصنف بالاسم أو الرقم<input name="q" defaultValue={q}/></label><button>بحث</button></form><p>تظهر أول ١٠٠ نتيجة؛ استخدم البحث للوصول إلى بقية العملاء والأصناف.</p><MappingForm choices={choices}/></section>}
 <section className="panel"><h2>المطابقات المحفوظة</h2><div className="tableWrap"><table><thead><tr><th>النوع</th><th>معرّف YCD OIL</th><th>رمز مداد</th><th>مرجع المحاسب</th><th>الإجراء</th></tr></thead><tbody>{mappings.map(m=><tr key={m.id}><td>{mappingLabels[m.kind]}</td><td>{Object.values(choices).flat().find(c=>c.id===m.localId)?.label??m.localId}</td><td>{m.remoteId}</td><td>{m.note}</td><td>{can&&<MedadForm action="unmap" values={{id:m.id}} label="إلغاء المطابقة"/>}</td></tr>)}</tbody></table></div><p>تعديل المطابقة يُبطل المسودات السابقة ويستدعي تجهيزها من جديد.</p></section>
 {can&&config&&<section className="panel"><h2>إضافة العمليات السابقة لقائمة المراجعة</h2><MedadForm action="scan" label="فحص العمليات وإضافتها دون تكرار"><label>من<input name="from" type="date" defaultValue={today} required/></label><label>إلى<input name="to" type="date" defaultValue={today} required/></label><p>الحد ٣١ يومًا و٥٠٠ عملية من كل نوع في الفحص الواحد. لا ينشئ الفحص فواتير أو قيودًا جديدة.</p></MedadForm></section>}
 <section className="panel"><h2>سجل المراجعة — الصفحة {Math.floor(page)}</h2><div className="tableWrap"><table><thead><tr><th>العملية</th><th>رقم المصدر</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>{entries.map(e=><tr key={e.id}><td>{kindLabels[e.kind]}</td><td><a href={`/dashboard/integrations/medad/${e.id}`}>{e.sourceNo}</a></td><td>{statusLabels[e.status]}</td><td>{can&&<MedadForm action="prepare" values={{id:e.id}} label="تجهيز / تحديث مسودة"/>}</td></tr>)}</tbody></table></div>{!entries.length&&<p>لا توجد عمليات في القائمة. فعّل الالتقاط أو افحص العمليات السابقة بعد حفظ الإعداد.</p>}<div className="actionStack">{page>1&&<a href={`?page=${Math.floor(page)-1}`}>السابق</a>}{entries.length===50&&<a href={`?page=${Math.floor(page)+1}`}>التالي</a>}</div></section></main>;
}
