import { redirect } from "next/navigation";
import { db } from "@/lib/db";
import { getSession } from "@/lib/auth";
import { PERMISSIONS as P, hasPermission } from "@/lib/rbac";
import { riyadhDateKey } from "@/lib/time";
import WashForm from "./wash-form";
const money = (v: unknown) => `${Number(v).toFixed(2)} ر.س`;
export default async function WashPage() {
  const session = await getSession();
  if (!session) redirect("/");
  if (!session.branchId || ![P.COUPON_REDEEM, P.FINANCE_VIEW, P.FINANCE_EXPENSE_APPROVE, P.FINANCE_EXPENSE_PAY].some(p => hasPermission(session.permissions, p))) redirect("/dashboard");
  const branchId = session.branchId; const can = (p: string) => hasPermission(session.permissions, p);
  const branch = await db.branch.findUniqueOrThrow({ where: { id: branchId } });
  const agreements = await db.washAgreement.findMany({ where: { OR: [{ sourceBranchId: branchId }, { washBranchId: branchId }] }, include: { sourceBranch: true, washBranch: true }, orderBy: { createdAt: "asc" } });
  const own = agreements.find(a => a.sourceBranchId === branchId);
  const services = await db.washService.findMany({ where: { agreementId: { in: agreements.map(a => a.id) } }, include: { agreement: true, coupon: { include: { invoice: { include: { customer: true, serviceOrder: { include: { vehicle: true } } } } } }, batch: true }, orderBy: { receivedAt: "desc" }, take: 100 });
  const batches = await db.washBatch.findMany({ where: { agreementId: { in: agreements.map(a => a.id) } }, include: { agreement: true, payments: true, services: { include: { coupon: true } } }, orderBy: { submittedAt: "desc" } });
  const config = can(P.USER_MANAGE) && can(P.FINANCE_MANAGE);
  const branches = config ? await db.branch.findMany({ where: { organizationId: branch.organizationId }, select: { id: true, nameAr: true } }) : [];
  const payBranches = agreements.filter(a => a.sourceBranchId === branchId).flatMap(a => [a.sourceBranchId, a.washBranchId]);
  const accounts = can(P.FINANCE_EXPENSE_PAY) ? await db.financialAccount.findMany({ where: { branchId: { in: payBranches }, active: true, type: { in: ["CASH", "BANK"] } }, orderBy: { nameAr: "asc" } }) : [];
  const posted = batches.filter(b => b.status === "POSTED");
  const due = posted.reduce((n,b) => n + Number(b.total), 0); const paid = posted.reduce((n,b) => n + b.payments.reduce((m,p) => m + Number(p.amount),0),0);
  return <main className="workspace">
    <div className="workspaceTop"><div><a className="backLink" href="/dashboard">← لوحة التحكم</a><h1>كوبونات غسيل السيارات — YCD OIL</h1><p>استقبال خدمات الكوبونات، رفع المطالبات اليومية، اعتماد المستحقات والسداد وكشف الحساب بين المركز والمغسلة.</p></div><img className="documentCenterLogo" src="/brand/ycd-logo-source.svg" alt="YCD OIL" /></div>
    <section className="kpis reportKpis"><article><span>المطالبات المرحلة</span><b>{money(due)}</b></article><article><span>المسدد</span><b>{money(paid)}</b></article><article><span>المتبقي للمغسلة</span><b>{money(due-paid)}</b></article><article><span>مطالبات بانتظار الاعتماد</span><b>{batches.filter(b=>b.status==="SUBMITTED").length}</b></article></section>
    <div className="actionStack"><a className="secondaryLink" href="/dashboard/service-orders?channel=WASH">استقبال عميل مباشر للمغسلة</a><a className="secondaryLink" href="/dashboard/loyalty">برنامج الولاء والغسلات المجانية</a><a className="secondaryLink" href="/dashboard/marketing">رسائل وعروض المراكز</a><a className="secondaryLink" href="/dashboard/coupons">بطاقات الكوبونات وطباعتها</a><a className="secondaryLink" href="/dashboard/service-orders">استقبال السيارات وأوامر الخدمة</a></div>
    {config && <details className="panel" open={!own}><summary>إعداد اتفاق التسوية وقيمة الكوبون</summary><p>القيمة هي كامل المستحق المتفق عليه لكل غسيل. اتركها فارغة إذا كانت تختلف حسب الخدمة؛ تُعتمد قيمة كل خدمة قبل رفع المطالبة. لا تتغير قيم الخدمات السابقة عند تعديل الاتفاق.</p><WashForm action="configure" label="حفظ اتفاق التسوية"><label>اسم المغسلة<input name="nameAr" defaultValue={own?.nameAr} required /></label><label>فرع المغسلة<select name="washBranchId" defaultValue={own?.washBranchId ?? branchId}>{branches.map(b=><option key={b.id} value={b.id}>{b.nameAr}</option>)}</select></label><label>قيمة التسوية الافتراضية — ر.س<input name="unitAmount" type="number" min="0.01" step="0.01" defaultValue={own?.unitAmount?.toString()} /></label><label>إصدار كوبون الغسيل<select name="issueMode" defaultValue={own?.issueMode ?? "ELIGIBLE"}><option value="ELIGIBLE">للأصناف والخدمات المؤهلة فقط</option><option value="ALL">لكل فاتورة خدمة</option></select></label><label>دورية السداد<select name="cadence" defaultValue={own?.cadence ?? "DAILY"}><option value="DAILY">يومي</option><option value="WEEKLY">أسبوعي</option><option value="MONTHLY">شهري</option></select></label><small>الدورية مرجع للتسوية؛ تنفيذ السداد يتطلب اعتماد المطالبة وتسجيل الدفعة. إذا كان المركزان على فرع واحد، استخدم حسابي صرف وقبض منفصلين.</small></WashForm></details>}
    {can(P.COUPON_REDEEM) && agreements.some(a=>a.washBranchId===branchId) && <section className="panel"><h2>خدمة غسيل جديدة</h2><p>مصدر الخدمة: كوبون خدمة من مركز YCD OIL. الكوبون يُستخدم مرة واحدة، ويرتبط بالعميل والسيارة والفاتورة الأصلية.</p><WashForm action="redeem" label="تحقق وافتح خدمة غسيل"><label>كود الكوبون<input name="serial" required placeholder="WASH-..." dir="ltr" /></label></WashForm></section>}
    <section className="panel"><h2>خدمات الغسيل — آخر ١٠٠ خدمة</h2><div className="tableWrap"><table><thead><tr><th>رقم الخدمة / الكوبون</th><th>العميل والسيارة</th><th>الفاتورة</th><th>الحالة</th><th>المستحق</th><th>الإجراء</th></tr></thead><tbody>{services.map(s=><tr key={s.id}><td>{s.serviceNo}<br/>{s.coupon.serial}</td><td>{s.coupon.invoice.customer.name}<br/>{s.coupon.invoice.serviceOrder.vehicle.plate}</td><td>{s.coupon.invoice.invoiceNo}</td><td>{s.status==="OPEN"?"قيد التنفيذ":"مكتملة"}<br/>{s.batch?.batchNo ?? "لم ترفع بمطالبة"}</td><td>{s.amount ? money(s.amount) : "بانتظار تحديد القيمة"}</td><td>{s.status==="OPEN" && s.agreement.washBranchId===branchId && can(P.COUPON_REDEEM) && <WashForm action="complete" values={{serviceId:s.id}} label="تأكيد إكمال الغسيل" />}{!s.batchId && s.agreement.sourceBranchId===branchId && can(P.FINANCE_MANAGE) && <WashForm action="value" values={{serviceId:s.id}} label="اعتماد قيمة الخدمة"><input aria-label="قيمة التسوية" name="amount" type="number" min="0.01" step="0.01" required defaultValue={s.amount?.toString()} /></WashForm>}</td></tr>)}{!services.length&&<tr><td colSpan={6}>لا توجد خدمات غسيل مسجلة.</td></tr>}</tbody></table></div></section>
    {agreements.map(a=><section className="panel" key={a.id}><h2>{a.sourceBranch.nameAr} ← {a.nameAr}</h2><p>دورية السداد: {({DAILY:"يومي",WEEKLY:"أسبوعي",MONTHLY:"شهري"} as Record<string,string>)[a.cadence]}</p><a className="secondaryLink" href={`/dashboard/wash/statement?agreementId=${a.id}`}>كشف حساب المركز والمغسلة</a>{a.washBranchId===branchId && can(P.COUPON_REDEEM)&&<WashForm action="submit" values={{agreementId:a.id}} label="رفع المطالبة اليومية" confirm="رفع جميع خدمات الغسيل المكتملة وغير المرفوعة لهذا التاريخ للمراجعة؟"><label>يوم إكمال الغسيل بتوقيت الرياض<input name="businessDate" type="date" defaultValue={riyadhDateKey(new Date())} max={riyadhDateKey(new Date())} required /></label></WashForm>}</section>)}
    <section className="panel"><h2>المطالبات والترحيل والسداد</h2>{batches.map(b=>{const paid=b.payments.reduce((n,p)=>n+Number(p.amount),0);const remaining=Number(b.total)-paid;return <article className="panel" key={b.id}><h3>{b.batchNo} — {b.businessDate}</h3><p>{b.agreement.nameAr} · {b.status==="SUBMITTED"?"بانتظار الاعتماد":b.status==="REJECTED"?"أعيدت للمراجعة":remaining<=0?"مرحلة ومسددّة":"مرحلة ومستحقة"} · الإجمالي {money(b.total)} · المسدد {money(paid)} · المتبقي {money(remaining)}</p><details><summary>تفاصيل الكوبونات والدفعات</summary><ul>{b.services.map(s=><li key={s.id}>{s.serviceNo} · {s.coupon.serial} · {money(s.amount)}</li>)}{b.payments.map(p=><li key={p.id}>سداد {p.settlementNo} · {money(p.amount)} · المرجع {p.reference} · {p.paidAt.toLocaleDateString("ar-SA-u-nu-latn",{timeZone:"Asia/Riyadh"})}</li>)}</ul></details>{b.agreement.sourceBranchId===branchId && b.status==="SUBMITTED" && can(P.FINANCE_EXPENSE_APPROVE)&&<><WashForm action="post" values={{batchId:b.id}} label="اعتماد وترحيل المستحق" confirm="اعتماد هذه المطالبة وإثباتها بكشف الحساب؟"/><WashForm action="reject" values={{batchId:b.id}} label="إعادة للمراجعة"/></>}{b.agreement.sourceBranchId===branchId&&b.status==="POSTED"&&remaining>0&&can(P.FINANCE_EXPENSE_PAY)&&<WashForm action="pay" values={{batchId:b.id}} label="تسجيل السداد والقبض" confirm="تسجيل دفعة مالية من حساب المركز إلى حساب المغسلة؟"><label>المبلغ<input name="amount" type="number" step="0.01" min="0.01" max={remaining.toFixed(2)} required /></label><label>حساب صرف المركز<select name="accountId" required><option value="">اختر الحساب</option>{accounts.filter(a=>a.branchId===b.agreement.sourceBranchId).map(a=><option key={a.id} value={a.id}>{a.nameAr}</option>)}</select></label><label>حساب قبض المغسلة<select name="receiptAccountId" required><option value="">اختر حسابًا منفصلًا للمغسلة</option>{accounts.filter(a=>a.branchId===b.agreement.washBranchId).map(a=><option key={a.id} value={a.id}>{a.nameAr}</option>)}</select></label><label>مرجع سند الدفع أو التحويل<input name="reference" required minLength={2}/></label></WashForm>}</article>})}{!batches.length&&<p>لا توجد مطالبات بعد.</p>}</section>
  </main>;
}
