// Observed at https://api-docs.medaderp.com/openapi.json, 2026-10-01 (Riyadh).
// Review drafts only; these definitions do not authorize remote accounting writes.
export const medadKinds = ["INVOICE", "PAYMENT", "RETURN", "WASH_CLAIM", "WASH_SETTLEMENT"] as const;
export type MedadKind = typeof medadKinds[number];
export const mappingKinds = ["CUSTOMER", "PRODUCT", "UNIT", "PAYMENT_METHOD", "VAT", "ACCOUNT"] as const;
export const kindLabels: Record<string,string> = { INVOICE:"فاتورة", PAYMENT:"تحصيل", RETURN:"مرتجع", WASH_CLAIM:"مطالبة غسيل", WASH_SETTLEMENT:"سداد المغسلة" };
export const mappingLabels: Record<string,string> = { CUSTOMER:"عميل", PRODUCT:"صنف أو خدمة", UNIT:"وحدة صنف", PAYMENT_METHOD:"طريقة سداد", VAT:"نوع الضريبة", ACCOUNT:"حساب مالي" };
export const statusLabels: Record<string,string> = { CAPTURED:"بانتظار التجهيز", PREPARED:"مسودة مراجعة — لم تُرسل", NEEDS_DATA:"بيانات أو مطابقة ناقصة", NOT_SUPPORTED:"يحتاج توضيحًا من مداد" };
export const issueLabels: Record<string,string> = {
  CONNECTION_REQUIRED:"أكمل بيانات اشتراك مداد والفرع.", INVOICE_AUTHORITY_REQUIRED:"حدد الجهة المقترحة لإصدار الفاتورة الرسمية بالتنسيق مع الحسابات.", WAREHOUSE_REQUIRED:"رقم مخزن مداد غير محدد.", CUSTOMER_MAPPING_REQUIRED:"طابق رقم العميل مع مداد.", PRODUCT_MAPPING_REQUIRED:"طابق أصناف الفاتورة مع مداد.", UNIT_MAPPING_REQUIRED:"طابق وحدات الأصناف مع مداد.", PAYMENT_MAPPING_REQUIRED:"طابق طريقة السداد مع دليل مداد.", VAT_MAPPING_REQUIRED:"طابق نوع الضريبة مع مداد.", MANUAL_ITEM_UNMAPPED:"يوجد بند حر دون صنف؛ يحتاج صنف خدمة معتمدًا في مداد.", SOURCE_CHANGED:"المصدر تغير؛ أعد تجهيز المسودة.", RETURNED_INVOICE_REVIEW:"هذه الفاتورة عليها مرتجع؛ راجع تسلسل الفاتورة والمرتجع.", INVALID_TOTALS:"إجمالي البنود لا يطابق الفاتورة.", INVALID_SOURCE:"العملية غير مكتملة أو غير قابلة للترحيل.", PAYMENT_POLICY_REQUIRED:"حدد سياسة ترحيل التحصيل منفصلًا عن الفاتورة لتجنب احتسابه مرتين.", PAYMENT_IDEMPOTENCY_UNDOCUMENTED:"واجهة الدفع لا توضح مرجعًا فريدًا أو آلية منع التكرار؛ الإرسال غير متاح.", RETURN_NUMBERING_UNCONFIRMED:"يلزم رقم فاتورة مداد وسياسة ترقيم المرتجع وتأكيد استجابته.", JOURNAL_ENDPOINT_UNDOCUMENTED:"لا توجد واجهة موثقة للقيود والتسويات بين المركزين في الدليل المتاح.", MIXED_PAYMENT_REVIEW:"توجد أكثر من طريقة سداد؛ يلزم تحديد طريقة تمثيلها في مداد.", ZERO_INVOICE_REVIEW:"فاتورة مجانية بالكامل؛ يلزم تأكيد معالجتها في مداد.", DRAFT_ONLY:"هذه مسودة للمراجعة؛ الإرسال إلى مداد غير مفعّل.", NUMBERING_ACK_REQUIRED:"يلزم تأكيد ترقيم فاتورة مداد وشكل رد النجاح قبل تفعيل الإرسال.", CONNECTION_NOT_CONFIGURED:"لم تُجهز بيانات الاتصال الآمن في الخادم.", REMOTE_AUTH_FAILED:"رفض مداد المصادقة؛ راجع بيانات الربط.", REMOTE_RESPONSE_INVALID:"استجابة مداد لا تطابق العقد المتوقع؛ تحتاج مراجعة.", REMOTE_UNAVAILABLE:"تعذر الاتصال بمداد؛ لم تُرسل أي عملية محاسبية.", FORBIDDEN:"ليست لديك صلاحية الربط المطلوبة.", INVALID_INPUT:"راجع الحقول المطلوبة.", LOCAL_ENTITY_NOT_FOUND:"البيان المحلي غير موجود أو لا يخص هذا الفرع.", REMOTE_MAPPING_CONFLICT:"رقم مداد مرتبط بعميل أو صنف آخر في الفرع.", STALE_DRAFT:"المسودة قديمة؛ أعد تجهيزها قبل تنزيلها.", ENTRY_NOT_FOUND:"العملية غير موجودة في الفرع الحالي.", READ_ONLY:"الإرسال المحاسبي غير متاح في هذه المرحلة.", CONCURRENT_CHANGE:"تغيرت البيانات؛ حدّث الصفحة وأعد المحاولة.", CONFIG_LOCKED:"لا يمكن تغيير حساب مداد أو سنته بعد وجود مطابقات أو مسودات؛ يلزم فصل إعدادات الحساب الجديد.", READ_CHECK_NOT_ENABLED:"اختبار الاتصال غير مفعّل في إعدادات الخادم.", UNSUPPORTED_REMOTE_HOST:"عنوان الاتصال غير معتمد أو يشير إلى موقع التوثيق.", EXPORT_LIMIT:"اختر مدة أقصر لعرض العمليات القديمة.", FISCAL_YEAR_MISMATCH:"تاريخ العملية لا يطابق السنة المالية المحددة للربط." };
